language: generic
os: linux
git:
  depth: false
compiler:
  - gcc
cache:
  ccache: true
env:
  global:
    - secure: "SnIBG/xLIHX3CSvUbqqsX8xTVqIqQ7fFS6HWO6KZQVBsT6yugTwYHbyhNiU531JejYJ/I3ZrDhXfYH3qFZiYxnH1sifvwV+fnTtMXpPN7qPZwIymkjcmm6gJF51e0C7VOfUbvKFv0ngwj+ul21rgZSMuoEvxPK0WxtE3/ZSfn9c="
    - APT_DEPENDENCIES="doxygen libeigen3-dev "
    - DEBSIGN_KEYID=5AE5CD75
    - LCOV_IGNORE_RULES="*unittest* /opt/openrobots/*"
    - DO_COVERAGE_ON_BRANCH="master;release"
    - DO_CPPCHECK_ON_BRANCH=""
    - DO_INSTALL_DOC_EXCEPT_ON_BRANCH=""
    - BUILDTYPE=Release
    - BUILD_WITH_CATKIN_SUPPORT=false
    - CTEST_OUTPUT_ON_FAILURE=1

branches:
  only:
    - master
    - debian
    - devel

jobs:
  include:
    - dist: bionic
      env: 
        - BUILD_WITH_COLLISION_SUPPORT=OFF
        - TRAVIS_PYTHON_VERSION=27
        - TRAVIS_PYTHON_VERSION_WITH_DOT=2.7
      python: 2.7
    - dist: bionic
      env: 
        - BUILD_WITH_COLLISION_SUPPORT=ON
        - TRAVIS_PYTHON_VERSION=27
        - TRAVIS_PYTHON_VERSION_WITH_DOT=2.7
      python: 2.7
    - dist: bionic
      env: 
        - BUILD_WITH_COLLISION_SUPPORT=ON
        - TRAVIS_PYTHON_VERSION=36
        - TRAVIS_PYTHON_VERSION_WITH_DOT=3.6
      python: 3.6

before_install: ./travis_custom/custom_before_install
install:
  - pip install --user pyopenssl
  - pip install --user numpy
script:
  - export CMAKE_ADDITIONAL_OPTIONS="-DCMAKE_BUILD_TYPE=${BUILDTYPE} -DBUILD_WITH_COLLISION_SUPPORT=${BUILD_WITH_COLLISION_SUPPORT} -DBUILD_ADVANCED_TESTING=ON"
  - export CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH
  - travis_wait 60 ./.travis/run ../travis_custom/custom_build
after_failure: ./.travis/run after_failure
after_success:
  - ./.travis/run after_success
