controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000
  legged_Perceptive_controller:
    type: legged/PerceptiveLeggedController
  legged_Cheater_Perceptive_controller:
    type: legged/PerceptiveLeggedCheaterController
