authors: []
blacklist: []
build_space: build_rel
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=RelWithDebInfo
- -DCMAKE_EXPORT_COMPILE_COMMANDS=Yes
devel_layout: linked
devel_space: devel_rel
extend_path: null
extends: null
install: false
install_space: install_rel
isolate_install: false
jobs_args: []
licenses:
- TODO
log_space: logs
maintainers: []
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
